version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@steebchen/*" # we separate @steebchen packages
    groups:
      abinnovision:
        patterns:
          - "@abinnovision/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      fortawesome:
        patterns:
          - "@fortawesome/*"
      next:
        patterns:
          - "@next/*"
          - "next"
      heroui:
        patterns:
          - "@heroui/*"
      drizzle:
        patterns:
          - "drizzle-kit"
          - "drizzle-orm"
      prisma:
        patterns:
          - "@prisma/client"
          - "prisma"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      radix:
        patterns:
          - "@radix-ui/*"

  - package-ecosystem: "npm"
    target-branch: main # this is a hack to make the same ecosystem group work
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@steebchen/*" # Restrict updates to @steebchen packages only
    groups:
      steebchen:
        patterns:
          - "@steebchen/*"
