services:
  # Main development container
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/llmgateway:cached
    command: sleep infinity
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:pw@postgres:5432/db

  postgres:
    image: postgres:17-alpine
    command: postgres -c log_statement=all
    restart: always
    ports:
      - "5388:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    volumes:
      - ../packages/db/init:/docker-entrypoint-initdb.d
