name: e2e
on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Provider to test"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - openai
          - anthropic
          - google-vertex

jobs:
  e2e:
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      cmd: pnpm run setup && pnpm test:e2e
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      VERTEX_API_KEY: ${{ secrets.VERTEX_API_KEY }}
