name: e2e
on:
  pull_request:
    paths:
      - "apps/gateway/**"
      - "packages/models/**"
      - ".github/workflows/e2e.yml"
jobs:
  e2e:
    uses: ./.github/workflows/run.yml
    secrets: inherit
    if: ${{ github.actor != 'dependabot[bot]' }}
    with:
      cmd: pnpm run setup && pnpm test:e2e
