name: e2e
on:
  push:
  # Keep the manual trigger option as well
  workflow_dispatch:
    inputs:
      provider:
        description: "Provider to test"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - openai
          - anthropic
          - google-vertex

jobs:
  e2e:
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      cmd: pnpm run setup && pnpm test:e2e
