name: ci

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, gateway, ui, docs]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push split
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/split.dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.app }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}-${{ matrix.app }}:latest
          target: ${{ matrix.app }}
          cache-from: type=gha,scope=${{ matrix.app }}
          cache-to: type=gha,mode=max,scope=${{ matrix.app }}
          build-args: |
            VITE_API_URL=${{ secrets.API_URL }}
            VITE_DOCS_URL=${{ secrets.DOCS_URL }}
            VITE_CRISP_ID=${{ secrets.CRISP_ID }}
            VITE_POSTHOG_KEY=${{ secrets.POSTHOG_KEY }}
            VITE_POSTHOG_HOST=${{ secrets.POSTHOG_HOST }}
            NEXT_PUBLIC_POSTHOG_HOST=${{ secrets.POSTHOG_KEY }}
            NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.POSTHOG_HOST }}

  push-unified:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push unified
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/unified.dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}-unified:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository }}-unified:latest
          cache-from: type=gha,scope=unified
          cache-to: type=gha,mode=max,scope=unified
