name: ci

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [api, gateway, ui, docs]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: get_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}-${{ matrix.app }}:${{ steps.get_sha.outputs.short_sha }}
            ghcr.io/${{ github.repository }}-${{ matrix.app }}:latest
          target: ${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_POSTHOG_HOST=${{ secrets.VITE_POSTHOG_HOST }}
            VITE_POSTHOG_KEY=${{ secrets.VITE_POSTHOG_KEY }}
